// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using API.Data;

#nullable enable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728120000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("API.Models.Moeda", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("DataCadastro")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DataAtualizacao")
                    .HasColumnType("TEXT");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<decimal>("Preco")
                    .HasColumnType("decimal(18,8)");

                b.Property<string>("Simbolo")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Simbolo")
                    .IsUnique();

                b.ToTable("Moedas", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
